train: ../../../data/train_threads_b/object_train_val/train/augmented
val: ../../../data/real_images/4_real_images/preprocessed-resized/annotated
test: ../../../data/real_images/3_real_imgs/test/images

# number of classes
nc: 4

# class names
names: ['nut', 'screw-small', 'washer', 'screw-large']