train: ../../data/training_data/train/
val: ../../data/training_data/val/
test: ../../data/test/

# number of classes
nc: 4

# class names
names: ['dst4', '210216-4x20', '210216-4x10', '10_00_0125_0084a_v4a']