train: ../../../data/train_threads_b/overlaying/train_val_split/train
val: ../../../data/train_threads_b/overlaying/train_val_split/val
test: ../../data/test/

# number of classes
nc: 5

# class names
names: ['nut', 'screw-small', 'washer', 'screw-large', 'assembly']