train: ../../../data/train_threads_b/overlaying/augmented
val: ../../../data/real_images/2_real_imgs/test
test: ../../data/test/

# number of classes
nc: 5

# class names
names: ['nut', 'screw-small', 'washer', 'screw-large', 'assembly']